# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Projekty\Programowanie\C++\InventoryGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Projekty\Programowanie\C++\InventoryGame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Projekty\Programowanie\C++\InventoryGame\CMakeFiles E:\Projekty\Programowanie\C++\InventoryGame\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Projekty\Programowanie\C++\InventoryGame\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named InventoryGame

# Build rule for target.
InventoryGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 InventoryGame
.PHONY : InventoryGame

# fast build rule for target.
InventoryGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/build
.PHONY : InventoryGame/fast

src/Inventory.obj: src/Inventory.cpp.obj
.PHONY : src/Inventory.obj

# target to build an object file
src/Inventory.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/Inventory.cpp.obj
.PHONY : src/Inventory.cpp.obj

src/Inventory.i: src/Inventory.cpp.i
.PHONY : src/Inventory.i

# target to preprocess a source file
src/Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/Inventory.cpp.i
.PHONY : src/Inventory.cpp.i

src/Inventory.s: src/Inventory.cpp.s
.PHONY : src/Inventory.s

# target to generate assembly for a file
src/Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/Inventory.cpp.s
.PHONY : src/Inventory.cpp.s

src/Item.obj: src/Item.cpp.obj
.PHONY : src/Item.obj

# target to build an object file
src/Item.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/Item.cpp.obj
.PHONY : src/Item.cpp.obj

src/Item.i: src/Item.cpp.i
.PHONY : src/Item.i

# target to preprocess a source file
src/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/Item.cpp.i
.PHONY : src/Item.cpp.i

src/Item.s: src/Item.cpp.s
.PHONY : src/Item.s

# target to generate assembly for a file
src/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/Item.cpp.s
.PHONY : src/Item.cpp.s

src/Player.obj: src/Player.cpp.obj
.PHONY : src/Player.obj

# target to build an object file
src/Player.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/Player.cpp.obj
.PHONY : src/Player.cpp.obj

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/UIButton.obj: src/UIButton.cpp.obj
.PHONY : src/UIButton.obj

# target to build an object file
src/UIButton.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/UIButton.cpp.obj
.PHONY : src/UIButton.cpp.obj

src/UIButton.i: src/UIButton.cpp.i
.PHONY : src/UIButton.i

# target to preprocess a source file
src/UIButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/UIButton.cpp.i
.PHONY : src/UIButton.cpp.i

src/UIButton.s: src/UIButton.cpp.s
.PHONY : src/UIButton.s

# target to generate assembly for a file
src/UIButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/UIButton.cpp.s
.PHONY : src/UIButton.cpp.s

src/UIElement.obj: src/UIElement.cpp.obj
.PHONY : src/UIElement.obj

# target to build an object file
src/UIElement.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/UIElement.cpp.obj
.PHONY : src/UIElement.cpp.obj

src/UIElement.i: src/UIElement.cpp.i
.PHONY : src/UIElement.i

# target to preprocess a source file
src/UIElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/UIElement.cpp.i
.PHONY : src/UIElement.cpp.i

src/UIElement.s: src/UIElement.cpp.s
.PHONY : src/UIElement.s

# target to generate assembly for a file
src/UIElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/UIElement.cpp.s
.PHONY : src/UIElement.cpp.s

src/UIImage.obj: src/UIImage.cpp.obj
.PHONY : src/UIImage.obj

# target to build an object file
src/UIImage.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/UIImage.cpp.obj
.PHONY : src/UIImage.cpp.obj

src/UIImage.i: src/UIImage.cpp.i
.PHONY : src/UIImage.i

# target to preprocess a source file
src/UIImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/UIImage.cpp.i
.PHONY : src/UIImage.cpp.i

src/UIImage.s: src/UIImage.cpp.s
.PHONY : src/UIImage.s

# target to generate assembly for a file
src/UIImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/UIImage.cpp.s
.PHONY : src/UIImage.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\InventoryGame.dir\build.make CMakeFiles/InventoryGame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... InventoryGame
	@echo ... src/Inventory.obj
	@echo ... src/Inventory.i
	@echo ... src/Inventory.s
	@echo ... src/Item.obj
	@echo ... src/Item.i
	@echo ... src/Item.s
	@echo ... src/Player.obj
	@echo ... src/Player.i
	@echo ... src/Player.s
	@echo ... src/UIButton.obj
	@echo ... src/UIButton.i
	@echo ... src/UIButton.s
	@echo ... src/UIElement.obj
	@echo ... src/UIElement.i
	@echo ... src/UIElement.s
	@echo ... src/UIImage.obj
	@echo ... src/UIImage.i
	@echo ... src/UIImage.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

