# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/Projekty/Programowanie/C++/InventoryGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/Projekty/Programowanie/C++/InventoryGame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/Projekty/Programowanie/C++/InventoryGame/CMakeFiles /mnt/e/Projekty/Programowanie/C++/InventoryGame//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/Projekty/Programowanie/C++/InventoryGame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named InventoryGame

# Build rule for target.
InventoryGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InventoryGame
.PHONY : InventoryGame

# fast build rule for target.
InventoryGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/build
.PHONY : InventoryGame/fast

src/Inventory.o: src/Inventory.cpp.o
.PHONY : src/Inventory.o

# target to build an object file
src/Inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/Inventory.cpp.o
.PHONY : src/Inventory.cpp.o

src/Inventory.i: src/Inventory.cpp.i
.PHONY : src/Inventory.i

# target to preprocess a source file
src/Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/Inventory.cpp.i
.PHONY : src/Inventory.cpp.i

src/Inventory.s: src/Inventory.cpp.s
.PHONY : src/Inventory.s

# target to generate assembly for a file
src/Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/Inventory.cpp.s
.PHONY : src/Inventory.cpp.s

src/Item.o: src/Item.cpp.o
.PHONY : src/Item.o

# target to build an object file
src/Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/Item.cpp.o
.PHONY : src/Item.cpp.o

src/Item.i: src/Item.cpp.i
.PHONY : src/Item.i

# target to preprocess a source file
src/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/Item.cpp.i
.PHONY : src/Item.cpp.i

src/Item.s: src/Item.cpp.s
.PHONY : src/Item.s

# target to generate assembly for a file
src/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/Item.cpp.s
.PHONY : src/Item.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/UIButton.o: src/UIButton.cpp.o
.PHONY : src/UIButton.o

# target to build an object file
src/UIButton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/UIButton.cpp.o
.PHONY : src/UIButton.cpp.o

src/UIButton.i: src/UIButton.cpp.i
.PHONY : src/UIButton.i

# target to preprocess a source file
src/UIButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/UIButton.cpp.i
.PHONY : src/UIButton.cpp.i

src/UIButton.s: src/UIButton.cpp.s
.PHONY : src/UIButton.s

# target to generate assembly for a file
src/UIButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/UIButton.cpp.s
.PHONY : src/UIButton.cpp.s

src/UIElement.o: src/UIElement.cpp.o
.PHONY : src/UIElement.o

# target to build an object file
src/UIElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/UIElement.cpp.o
.PHONY : src/UIElement.cpp.o

src/UIElement.i: src/UIElement.cpp.i
.PHONY : src/UIElement.i

# target to preprocess a source file
src/UIElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/UIElement.cpp.i
.PHONY : src/UIElement.cpp.i

src/UIElement.s: src/UIElement.cpp.s
.PHONY : src/UIElement.s

# target to generate assembly for a file
src/UIElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/UIElement.cpp.s
.PHONY : src/UIElement.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventoryGame.dir/build.make CMakeFiles/InventoryGame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... InventoryGame"
	@echo "... src/Inventory.o"
	@echo "... src/Inventory.i"
	@echo "... src/Inventory.s"
	@echo "... src/Item.o"
	@echo "... src/Item.i"
	@echo "... src/Item.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/UIButton.o"
	@echo "... src/UIButton.i"
	@echo "... src/UIButton.s"
	@echo "... src/UIElement.o"
	@echo "... src/UIElement.i"
	@echo "... src/UIElement.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

